# Generated by Django 5.2 on 2025-08-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='address',
        ),
        migrations.AddField(
            model_name='emp',
            name='salary',
            field=models.CharField(default=20000, max_length=10),
            preserve_default=False,
        ),
    ]
